spring:
 datasource:
  url: ${DB_URL:jdbc:postgresql://localhost:5434/financeflow}
  username: ${DB_USER:financeflow}
  password: ${DB_PASSWORD:financeflow}
 jpa:
  hibernate:
   ddl-auto: validate
  open-in-view: false
 flyway: {enabled: true}
server: {port: 8082}
